"""HTTP status constants and application error-code enum."""

from enum import Enum


class HttpStatus:
    """Named HTTP status codes used across all services."""

    OK: int = 200
    CREATED: int = 201
    NO_CONTENT: int = 204
    BAD_REQUEST: int = 400
    UNAUTHORIZED: int = 401
    FORBIDDEN: int = 403
    NOT_FOUND: int = 404
    CONFLICT: int = 409
    UNPROCESSABLE: int = 422
    TOO_MANY_REQUESTS: int = 429
    INTERNAL_ERROR: int = 500
    SERVICE_UNAVAILABLE: int = 503


class ErrorCode(str, Enum):
    """Machine-readable error codes returned in API responses."""

    # Auth
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
    AUTH_USER_EXISTS = "AUTH_USER_EXISTS"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_USER_INACTIVE = "AUTH_USER_INACTIVE"
    AUTH_OTP_INVALID = "AUTH_OTP_INVALID"
    AUTH_OTP_EXPIRED = "AUTH_OTP_EXPIRED"
    AUTH_PASSWORD_MISMATCH = "AUTH_PASSWORD_MISMATCH"
    AUTH_INSUFFICIENT_PERMISSIONS = "AUTH_INSUFFICIENT_PERMISSIONS"

    # Resource
    RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
    RESOURCE_EXISTS = "RESOURCE_EXISTS"
    RESOURCE_FORBIDDEN = "RESOURCE_FORBIDDEN"

    # Validation
    VALIDATION_ERROR = "VALIDATION_ERROR"
    MISSING_FIELD = "MISSING_FIELD"
    INVALID_FORMAT = "INVALID_FORMAT"

    # Infrastructure
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
    RATE_LIMITED = "RATE_LIMITED"

    # Agent
    AGENT_ERROR = "AGENT_ERROR"
    AGENT_TIMEOUT = "AGENT_TIMEOUT"
    AGENT_SESSION_NOT_FOUND = "AGENT_SESSION_NOT_FOUND"

    # Voice
    VOICE_AUDIO_TOO_LARGE = "VOICE_AUDIO_TOO_LARGE"
    VOICE_AUDIO_EMPTY = "VOICE_AUDIO_EMPTY"
    VOICE_STT_FAILED = "VOICE_STT_FAILED"
    VOICE_TTS_FAILED = "VOICE_TTS_FAILED"
    VOICE_PROCESSING_FAILED = "VOICE_PROCESSING_FAILED"
    VOICE_INVALID_FILE_TYPE = "VOICE_INVALID_FILE_TYPE"
    VOICE_FILE_TOO_LARGE = "VOICE_FILE_TOO_LARGE"

    # Schemes
    SCHEME_NOT_FOUND = "SCHEME_NOT_FOUND"
    SCHEME_SEARCH_FAILED = "SCHEME_SEARCH_FAILED"

    # Market
    MARKET_DATA_NOT_FOUND = "MARKET_DATA_NOT_FOUND"
    MARKET_QUERY_FAILED = "MARKET_QUERY_FAILED"

    # Geo
    GEO_PINCODE_NOT_FOUND = "GEO_PINCODE_NOT_FOUND"
    GEO_LOCATION_NOT_FOUND = "GEO_LOCATION_NOT_FOUND"

    # Admin
    ADMIN_USER_EXISTS = "ADMIN_USER_EXISTS"
    ADMIN_UNAUTHORIZED = "ADMIN_UNAUTHORIZED"
    ADMIN_CONFIG_ERROR = "ADMIN_CONFIG_ERROR"

    # Analytics
    ANALYTICS_NOT_AVAILABLE = "ANALYTICS_NOT_AVAILABLE"

    # Notification
    NOTIFICATION_LIMIT_EXCEEDED = "NOTIFICATION_LIMIT_EXCEEDED"

    # Misc
    PERMISSION_DENIED = "PERMISSION_DENIED"
    FIREBASE_ERROR = "FIREBASE_ERROR"
    MONGO_WRITE_FAILED = "MONGO_WRITE_FAILED"
    QDRANT_ERROR = "QDRANT_ERROR"

